### PR TITLE
Hotfix/encoding

### PR DESCRIPTION
**Pull request by iantanwx**
This fix addresses the following issues:
- 20 bytes from LSB instead of MSB
- Explicitly specify encoding as 'hex' when using `hash.js`, as it does _not_ assume strings to be hex encoded.

cc @edisonljh thanks!!!

### CODE REVIEW

**Comment by iantanwx** [comment]
The `sha256` function used here has been cross-checked with the C++ implementation with the following test:

```
BOOST_AUTO_TEST_CASE(SHA256_hex_encoding)
{
    struct test_pair
    {
        const unsigned char pubKey[151];
        const unsigned char digest[65];
    };

    struct test_pair pairs[] = {
        (struct test_pair){
            "04CFA555BB63231D167F643F1A23BA66E6CA1458D416DDB9941E95B5"
            "FD28DF0AC513075403C996EFBBC15D187868857E31CF7BE4D109B4F8"
            "CB3FD40499839F150A",
            "0E3E927F8BE54EB20F4F47BAA2F4D23649433591EA1B967127B971DE"
            "2288609E"},
        (struct test_pair){
            "04163FA604C65AEBEB7048C5548875C11418D6D106A20A0289D67B59"
            "807ABDD299D4CF0EFCF07E96E576732DAE122B9A8AC142214A6BC133"
            "B77AA5B79BA46B3E20",
            "F5B2DFDDFDBD0D13A67085A5AD5744C0C6246D9704592116FCCBF419"
            "78FE99C8"},
        (struct test_pair){
            "0485C34FF11EA1E06F44D35AFE3CC1748B6B122BB06DF021A4767DB4EF5FBCF1CD"
            "BED73C821D89724B59A0FC5E2F2E3E1A9C121D698FFF36D750EE463117438A14",
            "F8B9842A5F695139D22F49D1F706173B76FE0B5F680779558F23635A35425154"},
        (struct test_pair){
            "04C7D47AD99DD1DB85C9D0B6ABE89FFC137F230C991A33890C05436A14974543A2"
            "9D58BC4655269DB6BCD6EA27ADCA287F956355C64D676CEFCFEA14051B5239C9",
            "F6DAE5BBE10084A0AFCF363D11B08E4F6941D09DFBD39CE6474E115FF7908E05"},
        (struct test_pair){
            "0484929AB70D2B39703319A94144802EA9B9A7C8C1A673B10F01738DB5B5C40EA8"
            "F534BC21EF1B167FFCAC7D1A087ED5BE2A5D1FA720BC016FBFBD9FB869AEE4C6",
            "688C722F9C72CC4D760FD5967B3E26C3628BB4B3EB4B397AB7A2C3F26D312931"},
        (struct test_pair){
            "04DB0535D0E4337E5ADA6D87B07569308F3F3DE19AAD15BA1F95108E96F855E171"
            "95E5B86773F7570645832048CB5E13E1721784ECCE6BF69A0342F873E3AFEF58",
            "80A0001162A8230C4D3B624F8ACF90B9C4D9D8F625703936A1E02AECB7D84D41"},
        (struct test_pair){
            "04DC5CA31DFF767CB18F92D208FD74E36E800508D3B88BEE61680BB7CEFA051594"
            "3F2801D25BBCE9C6A65721427F2443532980A0F7B7AAE71B1FE0501179B8F641",
            "C3F72427150375B7F9838F1A82873A66FCFF822F529AD313E88C7785726F3EC1"},
        (struct test_pair){
            "04987F1F6A2FE56CD0C2461F2920E3E0D9BD9DE96A8FEBF9246E187E057C6141C4"
            "94B697455DCCEFA29361B976698594082ED962DA42BCE09EF0CE59BD05510DD4",
            "A26C10E3AFCAA7AA20F21BA513747D1A9BA8C1B91B32BFABE88072E9519BF0F9"},
        (struct test_pair){
            "04645A3995FF3309A36D1EC0991FD87ECE2EE36E8887F0D5B304ACCB9152FE7A60"
            "3ABA24FEFA904741E0FD67DB24432A38153ECDC496CEEC38EAB1B7C2D8405DE9",
            "5BE58C9BC87B284AF73274DC6DC01E38FAAA25DFAC9CBEB8941EA90C177D2CD8"},
        (struct test_pair){
            "04F3E03A4AC451A78254FA3D056448DB6CBC29D2EF429228C8435141A126C0C07F"
            "2446C68270016322E93A6A14F2E7C557BFDCC74E122A013498B7F1EBE008CC30",
            "0179E96DDEB567686E47F71794256DDBDBBFD5CA865B26D6751C66C84AA1EF4B"},
    };

    SHA2<HASH_TYPE::HASH_VARIANT_256> sha2;
    for (struct test_pair val : pairs)
    {
        vector<unsigned char> vec;
        vec = DataConversion::HexStrToUint8Vec((const char*)val.pubKey);
        sha2.Reset();
        sha2.Update(vec);

        vector<unsigned char> expected;
        expected = DataConversion::HexStrToUint8Vec((const char*)val.digest);
        vector<unsigned char> output = sha2.Finalize();

        LOG_GENERAL(INFO, val.digest);
        LOG_GENERAL(INFO, DataConversion::Uint8VecToHexStr(output));

        bool is_equal
            = std::equal(expected.begin(), expected.end(), output.begin());
        BOOST_CHECK_EQUAL(is_equal, true);
    }
}
```

The results are as follows:

```
[TID 410704][12:54:13][test_method                   ] 0E3E927F8BE54EB20F4F47BAA2F4D23649433591EA1B967127B971DE2288609E
[TID 410704][12:54:13][test_method                   ] 0E3E927F8BE54EB20F4F47BAA2F4D23649433591EA1B967127B971DE2288609E
[TID 410704][12:54:13][test_method                   ] F5B2DFDDFDBD0D13A67085A5AD5744C0C6246D9704592116FCCBF41978FE99C8
[TID 410704][12:54:13][test_method                   ] F5B2DFDDFDBD0D13A67085A5AD5744C0C6246D9704592116FCCBF41978FE99C8
[TID 410704][12:54:13][test_method                   ] F8B9842A5F695139D22F49D1F706173B76FE0B5F680779558F23635A35425154
[TID 410704][12:54:13][test_method                   ] F8B9842A5F695139D22F49D1F706173B76FE0B5F680779558F23635A35425154
[TID 410704][12:54:13][test_method                   ] F6DAE5BBE10084A0AFCF363D11B08E4F6941D09DFBD39CE6474E115FF7908E05
[TID 410704][12:54:13][test_method                   ] F6DAE5BBE10084A0AFCF363D11B08E4F6941D09DFBD39CE6474E115FF7908E05
[TID 410704][12:54:13][test_method                   ] 688C722F9C72CC4D760FD5967B3E26C3628BB4B3EB4B397AB7A2C3F26D312931
[TID 410704][12:54:13][test_method                   ] 688C722F9C72CC4D760FD5967B3E26C3628BB4B3EB4B397AB7A2C3F26D312931
[TID 410704][12:54:13][test_method                   ] 80A0001162A8230C4D3B624F8ACF90B9C4D9D8F625703936A1E02AECB7D84D41
[TID 410704][12:54:13][test_method                   ] 80A0001162A8230C4D3B624F8ACF90B9C4D9D8F625703936A1E02AECB7D84D41
[TID 410704][12:54:13][test_method                   ] C3F72427150375B7F9838F1A82873A66FCFF822F529AD313E88C7785726F3EC1
[TID 410704][12:54:13][test_method                   ] C3F72427150375B7F9838F1A82873A66FCFF822F529AD313E88C7785726F3EC1
[TID 410704][12:54:13][test_method                   ] A26C10E3AFCAA7AA20F21BA513747D1A9BA8C1B91B32BFABE88072E9519BF0F9
[TID 410704][12:54:13][test_method                   ] A26C10E3AFCAA7AA20F21BA513747D1A9BA8C1B91B32BFABE88072E9519BF0F9
[TID 410704][12:54:13][test_method                   ] 5BE58C9BC87B284AF73274DC6DC01E38FAAA25DFAC9CBEB8941EA90C177D2CD8
[TID 410704][12:54:13][test_method                   ] 5BE58C9BC87B284AF73274DC6DC01E38FAAA25DFAC9CBEB8941EA90C177D2CD8
[TID 410704][12:54:13][test_method                   ] 0179E96DDEB567686E47F71794256DDBDBBFD5CA865B26D6751C66C84AA1EF4B
[TID 410704][12:54:13][test_method                   ] 0179E96DDEB567686E47F71794256DDBDBBFD5CA865B26D6751C66C84AA1EF4B
```

**Comment by iantanwx** [comment]
@edisonljh I agree. I think someone from core should generate perhaps 10 more pairs in addition to the ones I have. On a separate note we should do the same for the Schorr implementation.

**Comment by iantanwx** [comment]
Regenerated the Schnorr signature values again, for completeness.

Test method:

```
BOOST_AUTO_TEST_CASE(test_sign)
{
    Schnorr& schnorr = Schnorr::GetInstance();


    int NUM_TEST = 10;

    // 1 MB message
    const unsigned int message_size = 88;

    for (int i = 0; i < NUM_TEST; i++)
    {
        pair<PrivKey, PubKey> keypair = schnorr.GenKeyPair();
        vector<unsigned char> message_rand(message_size);
        generate(message_rand.begin(), message_rand.end(), std::rand);

        LOG_GENERAL(INFO, "TEST CASE START");

        LOG_GENERAL(INFO,
                    "msg: " << DataConversion::Uint8VecToHexStr(message_rand));

        Signature signature;

        // Generate the signature
        BOOST_CHECK_MESSAGE(
            schnorr.Sign(message_rand, keypair.first, keypair.second, signature)
                == true,
            "Signing failed");

        // Check the generated signature
        BOOST_CHECK_MESSAGE(
            BN_cmp(signature.m_r.get(), schnorr.GetCurve().m_order.get()) == -1,
            "Signature generation check #1 failed");
        BOOST_CHECK_MESSAGE(BN_is_zero(signature.m_r.get()) != 1,
                            "Signature generation check #2 failed");
        BOOST_CHECK_MESSAGE(
            BN_cmp(signature.m_s.get(), schnorr.GetCurve().m_order.get()) == -1,
            "Signature generation check #3 failed");
        BOOST_CHECK_MESSAGE(BN_is_zero(signature.m_s.get()) != 1,
                            "Signature generation check #4 failed");
    }

    LOG_GENERAL(INFO, "TEST CASE END");
}

Output:
```
Running 6 test cases...
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: A7F1D92A82C8D8FE434D98558CE2B347171198542F112D0558F56BD68807999248336241F30D23E55F30D1C8ED610C4B0235398184B814A29CB45A672ACAE548E9C5F1B0C4158AE59B4D39F6F7E8A105D3FEEDA5D5F3D9E4
[TID 668923][14:52:01][Sign                          ] Private Key: 0755EFB1BDCA8E28FD29CA57774D9DB7B07A65A48EF7F8762E52840D43FDD277
[TID 668923][14:52:01][Sign                          ] Public Key: 02076F5B8511A3AD45A4856681AB66C0B8A979F44640036E752231298ED75AD48E
[TID 668923][14:52:01][Sign                          ] k: BC59D8D973767EBB04AE5BCDAD61849985E800D148165FAFF3AD93004EFB42D6
[TID 668923][14:52:01][Sign                          ] r: 76697A7A7BA544C21FB4B7EB64EF9E1C7CEA22C9CB861C9BB565D99C55767B82
[TID 668923][14:52:01][Sign                          ] s: 53354ADB50D95DB0608D999214FEB6D6E60FAF2323275162E023C09FB3FE3A04
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: 5BFA6CC351E220AE0CE106986D61FF34A11E19FD3650E9B7818FC33A1E0FC02C44557AC8AB50C9B2DEB2F6B5E24C4FDD9F8867BDCE1FF261008E7897970E346207D75E47A158298E5BA2F56246869CC42E362A02731264E6
[TID 668923][14:52:01][Sign                          ] Private Key: EF7AE484F4821E320D4104F5350B8A9B82121329CAF1596D1563B22595738536
[TID 668923][14:52:01][Sign                          ] Public Key: 0250E299F2A83E5E88C4B0A80D2CD5D6F4261E0E5B788F800AA332B4CE4CBC6AD0
[TID 668923][14:52:01][Sign                          ] k: 9B605C81169E65D8CABCC026834109027D07BC35DB4E60C094704CAD41436522
[TID 668923][14:52:01][Sign                          ] r: 3B5FC26609EC90B2CEC4A7D43BDC700D8BFA1A20E3AAB5C6A7DAFF4C9BB01C3B
[TID 668923][14:52:01][Sign                          ] s: 655568B30AFA1DFB60009F33DD9CBD8A4A44CC2A4A446FB7E0B2F84AE08828E5
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: 0687EF5309D108534F51F8658FB4F080B7CB19EE9AEBD718CC4FA27C8C37DFC1ADA5D133D13ABE03F021E9B1B78CCBD82F7FF2B38C6D48D01E481B2D4FAF7171805FD7F2D39EF4C4F19B9496E81DAB8193B3737E1B27D9C4
[TID 668923][14:52:01][Sign                          ] Private Key: 5E986AD51606AE69D9DA413B8FB503878BA607A31D12EA0B98B7930AC23662A7
[TID 668923][14:52:01][Sign                          ] Public Key: 031DFE3D937119F0DAC3BD4CD6DBF6E41FEB29C6B5C14EFB8E387AC4C4EFEB4036
[TID 668923][14:52:01][Sign                          ] k: 82BFDC4F8C897C46286109FA7B1B4ECCB724CE8823A27B01C0E857587587C71E
[TID 668923][14:52:01][Sign                          ] r: C200BC1708C1AEAFA624FB89ECB5FC8F92122D829ABB87FC8A14E27084FB7909
[TID 668923][14:52:01][Sign                          ] s: 48FDDFCD83AF62442380F3FF1E1A8F986196B56F2BE3F797EA991086F95CEDCE
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: 3957166441B93515E8F03C95D8E8CE1E1864FAAD68DDFC5932130109390B0F1FE5CA716805F8362E98DCCAADC86ADBED25801A9A9DCFA6264319DDAFE83A89C51F3C6D199D38DE10E660C37BE872C3F2B31660DE8BC95902
[TID 668923][14:52:01][Sign                          ] Private Key: 1A0A27DC91FC16956F2C18A9D3024DE4B3CEE9F330D4955E0655741929181DDF
[TID 668923][14:52:01][Sign                          ] Public Key: 0299831A1D3ECEDAC359355059D9D8CA3829CE4788B6D52873BE6811EA7926C0CD
[TID 668923][14:52:01][Sign                          ] k: CD9F19178563B5EE012E603C0F977E94E1D22A1FA98992177550E453AAEC0257
[TID 668923][14:52:01][Sign                          ] r: 391FE228C29165EAA4D3062CF96E2AA7C07B4F0F8D720CEC5162A3F16F653679
[TID 668923][14:52:01][Sign                          ] s: 513E0537B56E5CFCBE2CFB06022A280DE5BC224021B3BB06EF2BC78721903731
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: B9103262CDB941F77376F5D3DBB7A3D5A387797FC4819A035ECA704CEDB37110EE7F206B0C8805AAEBF4963E7C4708CE8D4E092366E71792A8A3B2BBCDEE321B3E15380C541EF0930888969F7457AFE18588826A419D5831
[TID 668923][14:52:01][Sign                          ] Private Key: 042E4F26C128D61B356C1C44DD8688945B9104CC064572137FF0C2238F3D1B26
[TID 668923][14:52:01][Sign                          ] Public Key: 02F898D30F7BE156B7AB89F92B5BE536D0BFADFF1343628DA68FAF24BBF8051F60
[TID 668923][14:52:01][Sign                          ] k: BC174CD51F7D19FF103CEA62AD9054387EFCBC9665991501C303549BACDF749B
[TID 668923][14:52:01][Sign                          ] r: 6E4CF5B29AE2F51645CB48FD0240B3D7A40F54FB87CD0CB6A81AE08086F87A9B
[TID 668923][14:52:01][Sign                          ] s: E68710FB6721EC077F7C57878CB7A79370CF7B4D056CE755C6761C166C39FB73
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: 1C1784B5484EECDB393F6A0ACA11B91DF0866B500B8DEE501FD7EB9BCE09A17D74124B4605ADFC0777BED9816D8D7E8488544A18D8045CB3283B0A752B881B5F500FADB59010E63D1B664F8BDA2DBF33CB6BE21C8EB3ECA9
[TID 668923][14:52:01][Sign                          ] Private Key: 8CEE0A6AEE8FB30A0AE7B6A5BFAFFA52E097E88F5388919F06D407520056503E
[TID 668923][14:52:01][Sign                          ] Public Key: 02D9CFD6CD6B4231BD6F1BDC5DAC502B4AF6144A9407FE37764CAB8CFC530566FA
[TID 668923][14:52:01][Sign                          ] k: 12C31321A6E3D10597C560DF6D4505ACF85E1531A56FC70EC65466BA79BAA7F7
[TID 668923][14:52:01][Sign                          ] r: AB561B9544923AA35F200AAF84206C4132E0F95629FD7CB7CBB211B4D88174F7
[TID 668923][14:52:01][Sign                          ] s: B65BAA2528FC5F3B195169EB6BFA2BD7B6D28B7B1323647105A7A733C0FEC4CE
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: D9D5BF144C08E9577ED0D1E5E560875109B340980580473DBC2E689A3BE838E77A0A3348FE960EC9BF81DA36F1868CA5D24788FA4C0C778BF0D12314285495636516CF40861B3D737FD35DBB591C5B5D25916EB1D86176B1
[TID 668923][14:52:01][Sign                          ] Private Key: 01310279230B5D9230AFAD6F72FD6AAB3584F0756833910278BCC54FDCFF2B45
[TID 668923][14:52:01][Sign                          ] Public Key: 03CB4F22931C82DE38780DEE9DB105CB7175287D65CF754D79165B2E50E4012E28
[TID 668923][14:52:01][Sign                          ] k: 6DF6E9E4A2CCCE53812CAA61477B93130F123782614BF61867653C966B03D689
[TID 668923][14:52:01][Sign                          ] r: 01F095B428B01F7243217C87839892E1EA44ABB22D3BC1FADBA774901218C1FD
[TID 668923][14:52:01][Sign                          ] s: 6A46F23B370EB837CBB8F52B99F4336FE4FE718C50270938B868314D9609D543
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: 4E0E67D2D03957F0CF6C87834BF328540588360BA7C7C5F88541634FB7BADE5F94FF671D1FEBDCBDA116D2DA779038ED7679896C29198B2657B58C50EA054F644F4129C8BA8D8D544B727633DD40754398046796E038626F
[TID 668923][14:52:01][Sign                          ] Private Key: 8608065C1B777CE7655311293995AA091C84C2B16B010985138936A6736EF0F6
[TID 668923][14:52:01][Sign                          ] Public Key: 03707675447CB9E50CDF2DDD4B3D0B2A5CFE2DE60AD377509E340E9D0B75F7458B
[TID 668923][14:52:01][Sign                          ] k: 8695F6766BA6D132E4EB547AFC9B65C0EE5F2AEC1D0F41E695ABCD161EAC9A52
[TID 668923][14:52:01][Sign                          ] r: 9CFB236E54868BE966A5104051EB9E1BB7F38B5BA30D2AA865E73F1BABE6C283
[TID 668923][14:52:01][Sign                          ] s: 4A213BC595BE4A6B91BDC2989041EFEACDD5E09EADEE21AEF6110A32C57C3317
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: EF9237CE5B615BC08677EE5ABFBD85F73F7F8868CB1B5FBA4C1309F16061AA133821FBE2A758D2BBE6AA040A940D41B7D3B869CEE945150AA4A40E6FF719EEC24B2681CD5CE06B50273436584066046656D5EFED73157591
[TID 668923][14:52:01][Sign                          ] Private Key: C7A5FCF7B927D652231C56CB8F007D2E4A392726620D6604B50F54BC32732A16
[TID 668923][14:52:01][Sign                          ] Public Key: 024F39C9B8DC1355E806F5C324A8D80B67FD0B1848A2A78F7C7E9E514ED9C51074
[TID 668923][14:52:01][Sign                          ] k: 015B931D9C7BF3A7A70E57868BF29712377E74355FC59032CD7547C80E179010
[TID 668923][14:52:01][Sign                          ] r: 611FAB2F8B1D0E48D2D535CD9A1DFD9F31AB834F8C34C20100FC93CBA61EEF72
[TID 668923][14:52:01][Sign                          ] s: 371DC25E061CF20F096AA2B1FE552A7C07D8B102B2F7F8865E984BA679CAF4AF
[TID 668923][14:52:01][test_method                   ] TEST CASE START
[TID 668923][14:52:01][test_method                   ] msg: 89D68815DDB9E5F8D7FD53B6EC096616A773B9421F6704CED36EF4E484BA0C6C5A4855C71C33A54AC82BE803E5CFD175779FC444B7E6AA9001EEFABEBC0CF99754887C7B0A27AFDDC415F8A02C5AF1EFEA26AD1E5D92B1E2
[TID 668923][14:52:01][Sign                          ] Private Key: EDA7AFB6E3CEC979CC37BA87A09E63CAA864D0202A6BA7DF7966C012B1D92F7E
[TID 668923][14:52:01][Sign                          ] Public Key: 024C34E2D3921D05102BF3D4EE806E188395AFD033F39D090A46A369D709797FC3
[TID 668923][14:52:01][Sign                          ] k: 63C6C74C9FD5F31B5576E47873994BB6C8724FA31EEAB7669DB915EDFDB1A23C
[TID 668923][14:52:01][Sign                          ] r: 4B31EA76A9E890D533A753BEB0EE9DE1072CA5508B0DA5D45B1AA9487FA491FE
[TID 668923][14:52:01][Sign                          ] s: CC92A532CCB5172C1199178E832EA770B4BFA696034471BDC1CE23215276B109
[TID 668923][14:52:01][test_method                   ] TEST CASE END
```

**Comment by Gnnng** [comment]
Just added 10 keypairs with the corresponding wallet addresses. These are generated using the existing utils (commands are also attached, which should work from the repo's root after you run `./build.sh`)

public key + private key

```
for i in {1..10}; do ./build/bin/genkeypair; echo; done > keys.txt
```

```
0314738163B9BB67AD11AA464FE69A1147DF263E8970D7DCFD8F993DDD39E81BD9 B4EB8E8B343E2CCE46DB4E7571EC1D9654693CCA200BC41CC20148355CA62ED9
034CE268AC5A340038D8ACEBBDD7363611A5B1197916775E32481F5D6B104FAF65 FD906F4A20A0507813FCB0D8D166CF45C1B17F217B776A003B3C3CC628C7E513
02FA7A501F323CC53E070C0A945370368679E7572960EC24D8A0387EF3B50A2285 C1FE69C394EE8564D0EA525FF74E5F37DF5267CF5C74F2E224757B7D9E594B73
036F8676E473AF20B4CCE7D327103DE4504A9C00EAE7EA03D0A365FB48817AC97F F197920FF83E3BD727560E1E08A4825910E3AA772B40EC4DEFFE241EE3A51D20
034C39363529C2D4078F72B8C498C4CBC5BA5E10D8666FE06F104A27E0E44242A0 3D0C4009DA5B4630D292E93FC8DF7A55E9B8B31E182A50D113DE6E7A7A728B5B
026DA5BF6C3A3C91C08A3DD7FBCE0BEAF5D436039C97B07A0F61AA4B9493E46787 8A06825735F2F374E5F60F0E08E06EF7169E2AE47532B741700574B9E1603DC0
032A661F9D4AB8DD9818CED2F62F3DA14FDD23E68E58D01A4AE186231D7FB609BB 715AB4286ECCB4E8E3AEC0AA8B6FB0E13C105B727E89AAE449F87F5DF4CFA53F
036A94E925BB200DCE41A46C9026E023B226DD5B4CB227CE766D60CC8FAB218148 B9056706EF197125598E7D5CA5AC9C47339B5C894C0656D33113052470BAF149
0247F13639C7597C8AE2467DD29D219C2749260F690D4069930FDEB7866B2BC1FA A6DEDD1BE3A36945517A6C8A0E1353414DEBC04C50C9E036361C2A2D95EEF947
02883100F00EAB9FB6FD79034BBA84235C22ED642470FF6C1DB7CF7F782902D9DC 57489B87A3E726267EC5150FAB6E202694E806EC8FBBE386572CDE640BB3EE4B
```

wallet addresses

```
for i in $(cat keys.txt); do echo $i | cut -f1 -d' ' | ./build/tests/Crypto/GetAddressFromPubKey | tr '[:lower:]' '[:upper:]'; done
```

```
4BAF5FADA8E5DB92C3D3242618C5B47133AE003C
448261915A80CDE9BDE7C7A791685200D3A0BF4E
DED02FD979FC2E55C0243BD2F52DF022C40ADA1E
13F06E60297BEA6A3C402F6F64C416A6B31E586E
1A90C25307C3CC71958A83FA213A2362D859CF33
625ABAEBD87DAE9AB128F3B3AE99688813D9C5DF
36BA34097F861191C48C839C9B1A8B5912F583CF
D2453AE76C9A86AAE544FCA699DBDC5C576AEF3A
72220E84947C36118CDBC580454DFAA3B918CD97
50F92304C892D94A385CA6CE6CD6950CE9A36839
```

**Comment by iantanwx** [comment]
Thank you very much @Gnnng !

**Comment by iantanwx** [comment]
@edisonljh @AmritKumar I have incorporated the keypairs/addresses generated by @Gnnng

**Comment by edisonljh** [comment]
Thanks @iantanwx , @AmritKumar this PR is ready to be merged. I've validated that the tests passed.

**Pull request merged**
