### PR TITLE
Correctly populate data and code

### LINKED ISSUE #213: zilliqa.provider.getTransaction doesn't return data field correctly
Code sample:

``` typescript
  const zilliqa = new Zilliqa('https://api.zilliqa.com');
  const hash =
    '92bf80c619f7e745fd141631a3616602be5cad067abc45c1e4571555a116f862';

  const transaction1 = await zilliqa.provider.send('GetTransaction', hash);
  const transaction2 = await zilliqa.blockchain.getTransaction(hash);
  console.log({
    data1: transaction1.result.data,
    data2: transaction2.txParams.data,
  });
```

**Expected behavior**

Both return same data

** Actual Result **

```
{
  data1: '{"_tag":"bestow","params":[{"vname":"label","value":"420somewhere","type":"String"},{"vname":"owner","value":"0x912c76ee4313fbd9ef20f80143569a5acb667bc8","type":"ByStr20"},{"vname":"resolver","value":"0x0000000000000000000000000000000000000000","type":"ByStr20"}]}',
  data2: ''
}
```

### PR DESCRIPTION
**Pull request by bogdan**
Fixes #213

### CODE REVIEW

**Comment by renlulu** [comment]
Hey, thanks for this pr, but I noticed that some unit tests are broken because of the change, it will be great if you can change the related unit tests as well, thanks!

**Comment by renlulu** [comment]
> Hey, thanks for this pr, but I noticed that some unit tests are broken because of the change, it will be great if you can change the related unit tests as well, thanks!

Or I can push the test fix to your branch, are you willing to allow me to do this : D @bogdan

**Comment by bogdan** [comment]
@renlulu I've given you access.

**Comment by renlulu** [comment]
@bogdan I have fixed the testing error. But can we switch the target branch to dev? thanks!

**Comment by renlulu** [comment]
Hey, I feel like it's too complicated and time wasting to solve the conflicts here, shall I do another simple PR for you? basically I know the issue are, thanks!

**Comment by bogdan** [comment]
@renlulu whatever works for you.

**Comment by renlulu** [comment]
> @renlulu whatever works for you.

OK thanks a lot. I'll just close this for now, thanks again!

**Pull request closed without merging**
