### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by noelyoo**
## Description

This PR 
* adds `prettier`, `.editorconfig`, `.prettierrc`,  `.prettierignore`
* formats code with `npm run prettier`

I referenced these repos for the setup: 
* https://github.com/0xProject/0x-monorepo
* https://github.com/loomnetwork/loom-js

background:
I discovered this extends:
```
"extends": [
    "tslint:latest",
    "tslint-config-prettier"
  ],
```
Therefore, I figured out it needs to be set up with prettier properly.
I will continue with tslint for the next PR depending on your feedback.

## Review Suggestion

a. Consideration for using prettier
b. Checking diffs  

Since this PR is just formatting code it should work as expected. Plus, all test passed.

### CODE REVIEW

**Comment by noelyoo** [comment]
@cheetahhh Sure. Before enhance this PR with `pre-commit`, let's hear other opinions about `Prettier` first. What do you think about this Ian? @iantanwx

**Comment by iantanwx** [comment]
I actually use vim-prettier to format on write. Can you add this commit to feature/monorepo @NoelYoo?

**Comment by noelyoo** [comment]
@iantanwx I committed this to `/feature/monorepo` and referenced [this](https://github.com/Zilliqa/savant-ide/blob/master/.prettierrc) for `.pretterrc`

**Comment by iantanwx** [comment]
Thank you so much @noelyoo 👍

**Pull request merged**
