### PR TITLE
feat/support-node-14

### PR DESCRIPTION
**Pull request by teye**
This pr updates Node version support from 12 to 14 (latest LTS).

This pr also includes minor updates to some of the packages in order to resolve `yarn bundle` issues on Windows on Node 14:
- `@types/node` 12.7.12 -> 14.14.22
- `protobufjs` 6.8.8 -> 6.10.2

This pr also removes the need for `web3-eth` to be installed. `web3-eth` was used previously to generate a `keystores.json` file to used for testcases for `zilliqa-js-account`.  The new test accounts are now generated using `zilliqa-js/crypto` to a new `keystores_redux.json` file. 

> Coincidentally, the removal of `web3-eth` also removes the requirement for a `js-sha3` module which in turns removes the need for Visual Studio Build Tools to be installed on Windows when performing a `yarn install`.

The branch is tested with the following node LTS versions / functions and on both **Windows 10 10.0.19041 Build 19041** and **Ubuntu 18.04** :
- Node 14.15.4 / 12.20.1 / 10.23.1
- yarn install
- yarn bootstrap
- yarn test
- yarn build:web
- yarn bundle
- examples/webpack/html
- examples/webpack/react

### CODE REVIEW

**Comment by hicaru** [comment]
For migrate nodejs 14 need change [package.json](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/packages/zilliqa/package.json#L34) too.

**Comment by bb111189** [comment]
help me rename
    "Zilliqa Usability Team <maintainer@zilliqa.com> (https://github.com/zilliqa/)" to Zilliqa Usability Team <maintainers@zilliqa.com> (https://github.com/zilliqa/)

**Comment by teye** [comment]
@hicaru 
> For migrate nodejs 14 need change [package.json](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/packages/zilliqa/package.json#L34) too.

Thanks. Already changed.
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/175c614a014fcfbe7c5761047c3cf18bf3efa6ad/packages/zilliqa/package.json

**Comment by bb111189** [comment]
Due to webpack changes, @teye  will need you to fix conflict and regenerate the min.js

**Comment by bb111189** [comment]
@teye can also update https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/.travis.yml so that the travis and build and test it?

**Review by bb111189 — APPROVED** [review]

**Pull request merged**
