### PR TITLE
Minimize jest related deps

### PR DESCRIPTION
**Pull request by noel-yoo**
## Description
This PR drops `jest-json-schema`, `jest-watch-typeahead` and removes the related codes and files to minimize jest related dependencies which are non-essential.

Also it removes the old integration tests which are not included in CI. 
I think we can focus on more unit testing and rewrite integration tests after that.

## Motivation and Context
To upgrade Jest for #356, we will face some breaking changes. To handle those changes in simpler and easier way, we can reduce the complexity for the deps when the deps are not essential.

## How has this been tested?
`yarn bootstrap && yarn test`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Add tests to cover changes as needed.
- [x] Update documentation as needed.

### CODE REVIEW

**Review by bb111189 — APPROVED** [review]

**Comment by noel-yoo** [comment]
resolved conflicts @bb111189

**Comment by noel-yoo** [comment]
I've also removed integration tests which covers `contracts` and `blockchain`.

**Comment by noel-yoo** [comment]
Also it removes the integration tests which are not included in CI.
I think we can focus on more unit testing and rewrite integration tests after that.

**Review by bb111189 — APPROVED** [review]
Additional commits LGTM

**Pull request merged**
