### PR TITLE
Track yarn.lock

### PR DESCRIPTION
**Pull request by noelyoo**
## Description

This PR tracks `yarn.lock` or `package-lock.json` file.

`yarn.lock` or `package-lock.json` file has been ignored since https://github.com/Zilliqa/Zilliqa-JavaScript-Library/commit/9083186494e5469fc2c07f2bb1da7db9a92f7b0e.

In order to get consistent installs across machines, Yarn needs more information than the dependencies you configure in your package.json. Yarn needs to store exactly which versions of each dependency were installed.

[source: https://docs.npmjs.com/files/package-lock.json]
[source: https://yarnpkg.com/lang/en/docs/yarn-lock/]

### CODE REVIEW

**Comment by noelyoo** [comment]
@mickys Oh, It's because I added newline there.
image

Since It's related with the PR https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/69, I will remote the newline in this PR. Thanks.

**Comment by mickys** [comment]
Looks good.

**Comment by noelyoo** [comment]
@iantanwx Hi Ian, I just added yarn.lock file 😄

**Comment by mickys** [comment]
I removed both lock files as usually they're meant for publishing and not development repos.

If things break they should break on development branches so you know about it.

Feel free to add them back.

**Comment by iantanwx** [comment]
@mickys @noelyoo let's just leave the lock files in for now. Thanks! Merging this.

**Pull request merged**
